# List

<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

*Jawaban*: **Semua jenis tipe data dapat dimasukkan ke dalam List, seperti integer, float, string, boolean, dictionary, set, tuple, bahkan List dalam List.**

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [1]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
a[1:5]

['13b', 'aa1', 1.32, 22.1]

Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [2]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
print([a, c, b])

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]


Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [3]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
a[1][1:]

[0, 6]

Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [4]:
p = [0, 5, 2, 10, 4, 9]
# ordered list
print(sorted(p, reverse=False))
# get max value of list
print(max(p))

[0, 2, 4, 5, 9, 10]
10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [12]:
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
b.extend(a)
print(b)

[5, 1, 3, 1, 3, 5]


Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [13]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2] = 10
# change list value
a[1][0] = 11
print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [21]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del areas[8:10]
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [22]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [item for item in S if item % 2 == 0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [23]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
print(europe.keys())
# print nilai dari key franche
print(europe['france'])

dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [27]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe['itali'] = 'roma'

# cek apakah itali ada di dalam objek dictionary
print('itali' in europe)

True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [28]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe['germany'] = 'berlin'

# remove australia dari europa
europe.pop('australia')

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [29]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country['indonesia'] = {'capital': 'jakarta', 'population': 250}

print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [31]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for key,value in country.items():
    print('Ibukota '+key+' adalah '+value['capital'])

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

# Tambahan Tugas Hari 4

<h2>1. Remove Duplicate List</h2>

Buatlah sebuah fungsi, yang menerima suatu argument objek list, dan return sebuah objek list baru, dimana objek list baru ini berisi list sebelumnya dikurangi dengan data yang duplikat, sehingga setiap element di dalam list adalah unik.

Berikan 2 solusi, solusi pertama menggunakan loop dan list, solusi yang kedua menggunakan objek set!

Hint:

In [38]:
# solusi tanpa menggunakan set
def remove_duplicate(obj_list):
    new_list = []
    for item in obj_list:
      if item not in new_list:
        new_list.append(item)
      else:
        continue
    return new_list

# solusi dengan menggunakan set
def remove_duplicate_with_set(obj_list):
    new_list = set(obj_list)
    return list(new_list)

obj_list = [1, 2, 4, 6, 2, 1, 4, 5, 7, 8, 6]
print(remove_duplicate(obj_list))
print(remove_duplicate_with_set(obj_list))

[1, 2, 4, 6, 5, 7, 8]
[1, 2, 4, 5, 6, 7, 8]


Expected Output :

[1, 2, 4, 6, 5, 7, 8]

[1, 2, 4, 5, 6, 7, 8]

<h2>2. Membuat ChatBot Sederhana</h2>

Buatlah sebuah fungsi chatbot yang memberikan suatu **respon** dimana chatbot ini menerima **satu argument string.**

Buah sebuah fungsi chatbot yang memberikan suatu **respon** dimana chatbot ini menerima **satu argument string.**

Jika argument adalah **pertanyaan** kemudian chatbot mengecek lagi apakah pertanyaan tersebut adalah pertanyaan **yang bisa di jawab atau tidak. Jika** pertanyaannya bisa di jawab maka fungsi akan memberikan jawaban yang bersifat **random** berdasarkan **opsi** list jawaban yang disediakan berdasarkan jenis pertanyaan tersebut. **Jika tidak** maka chatbot akan memberikan **jawaban default** bahwa chatbot tidak mengerti pertanyaannya.

Jika argument adalah bukan pertanyaan maka chatbot akan memberikan sebuah statement random yang disediakan.

Hint:

In [70]:
# import library
from datetime import datetime
import random

# ganti dengan sebuah nama
nama  = "Ari Wilyan Ramadhelza"
# variabel tanggal
tanggal = datetime.now().day
# default variabel untuk pertanyaan tidak diketahui
default = "maaf, aku tidak tahu jawaban dari pertanyaanmu"

# Membuat objek dictionary berisi berbagai opsi jawaban

# list jawaban untuk pertanyaan tentang nama
jawaban_nama = [
      "nama saya  {0}".format(nama),
      "orang-orang memanggil saya {0}".format(nama),
      "panggil saja saya {0}".format(nama)
   ]

# list jawaban untuk pertanyaan tentang tanggal
jawaban_tanggal = [
      "hari ini tanggal {0}".format(tanggal),
      "ya ampun masa tidak tahu, hari ini tanggal {0}".format(tanggal)
    ]

# opsi pertanyaan yang bisa dijawab
pertanyaan = {
  "nama kamu siapa?": jawaban_nama,
  "kamu siapa?" : jawaban_nama,
  "tanggal berapa hari ini?": jawaban_tanggal,
  "hari ini tanggal berapa?" : jawaban_tanggal,
  "default": default
}

# list jawaban untuk sebuah argument selain pertanyaan
statement =  [
                  'ceritakan lebih banyak!',
                  'kenapa kamu berpikir begitu?',
                  'sudah berapa lama kamu merasa seperti ini?',
                  'Itu sangat menarik!',
                  'oh wow!',
                  ':)'
              ]

# respon keseluruhan
responses = {
    'pertanyaan' : pertanyaan,
    'statement' : statement
}
#------
             
# ayo buat chatbotmu
def chatbot(message):
    ## code disini
    if (message[-1] == '?'):
      getPertanyaan = responses['pertanyaan']
      for key,value in getPertanyaan.items():
        if key == message:
          reply = random.choice(value)
          return reply
        elif key == "default":
          return value
        else:
          continue
    else:
      reply = random.choice(responses['statement'])
      return reply

print(chatbot('Selamat Pagi'))
print(chatbot('Mau bermain bersamaku?'))
print(chatbot('nama kamu siapa?'))
print(chatbot('hari ini tanggal berapa?'))

oh wow!
maaf, aku tidak tahu jawaban dari pertanyaanmu
panggil saja saya Ari Wilyan Ramadhelza
hari ini tanggal 2


Expected Output :

:)

maaf, aku tidak tahu jawaban dari pertanyaanmu

orang-orang memanggil saya Nama Anda

ya ampun masa tidak tahu, hari ini tanggal

<h2>Penjelasan</h2>

- Pada code yang ini print(chatbot(‘Selamat Pagi’)), chatbot melihat list opsi jawaban yang ada pada variabel statement, kemudian memilih secara random jawaban yang akan diberikan.

- Pada code yang ini print(chatbot(‘Mau bermain bersamaku?’)), chatbot melihat bahwa pesan ini adalah sebuah pertanyaan karena di akhiri dengan tanda tanya, kemudian value dari key ‘default’ karena pertanyaan tersebut tidak bisa dijawab oleh chatbot.

- Pada code yang ini print(chatbot(‘nama kamu siapa?’)), chatbot melihat bahwa pesan ini adalah sebuah pertanyaan karena di akhiri dengan tanda tanya, kemudian melihat pada variabel ‘jawaban_nama’ dan memilih secara random jawaban yang akan di berikan.

- Pada code yang ini print(chatbot(‘hari ini tanggal berapa?’)), chatbot melihat bahwa pesan ini adalah sebuah pertanyaan karena di akhiri dengan tanda tanya, melihat pada variabel ‘jawaban_tanggal’ dan memilih secara random jawaban yang akan diberikan.

<h2>Lingkup Materi :</h2>

- String

- Dictionary

- If-elif-else

- Fungsi

- List

- Library/Module Random